### ISSUE TITLE
demo中点快了会闪退...

### ISSUE THREAD

**Issue by CivelXu** [JmoVxia/CLInputToolbar#1]
*** Terminating app due to uncaught exception 'UIViewControllerHierarchyInconsistency', reason: 'child view controller:<UICompatibilityInputViewController: 0x115129570> should have parent view controller:(null) but actual parent is:<UIInputWindowController: 0x113857a00>'

**Comment by JmoVxia** [comment]
设置了inputAccessoryView，又将view添加到keyWindow引起崩溃，已经修复
